/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInstitutionsRouteImport } from './routes/api/institutions'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGenerateActivityRouteImport } from './routes/api/generate-activity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstitutionsRoute = ApiInstitutionsRouteImport.update({
  id: '/api/institutions',
  path: '/api/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateActivityRoute = ApiGenerateActivityRouteImport.update({
  id: '/api/generate-activity',
  path: '/api/generate-activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-activity': typeof ApiGenerateActivityRoute
  '/api/health': typeof ApiHealthRoute
  '/api/institutions': typeof ApiInstitutionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-activity': typeof ApiGenerateActivityRoute
  '/api/health': typeof ApiHealthRoute
  '/api/institutions': typeof ApiInstitutionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-activity': typeof ApiGenerateActivityRoute
  '/api/health': typeof ApiHealthRoute
  '/api/institutions': typeof ApiInstitutionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/generate-activity'
    | '/api/health'
    | '/api/institutions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/generate-activity' | '/api/health' | '/api/institutions'
  id:
    | '__root__'
    | '/'
    | '/api/generate-activity'
    | '/api/health'
    | '/api/institutions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateActivityRoute: typeof ApiGenerateActivityRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInstitutionsRoute: typeof ApiInstitutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/institutions': {
      id: '/api/institutions'
      path: '/api/institutions'
      fullPath: '/api/institutions'
      preLoaderRoute: typeof ApiInstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-activity': {
      id: '/api/generate-activity'
      path: '/api/generate-activity'
      fullPath: '/api/generate-activity'
      preLoaderRoute: typeof ApiGenerateActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateActivityRoute: ApiGenerateActivityRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInstitutionsRoute: ApiInstitutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
